version: 0.2

phases:
  install:
    commands:
        - wget https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
        - unzip terraform_0.13.2_linux_amd64.zip
        - mv terraform /bin
        - rm terraform_0.13.2_linux_amd64.zip
        - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.40/terragrunt_linux_amd64
        - mv terragrunt_linux_amd64 /bin/terragrunt
        - chmod +x /bin/terragrunt
        - npm install -g serverless 
        - npm install
  build:
    commands:
        - terraform init
        - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'